### ISSUE TITLE
No carga objeto JSON

### ISSUE THREAD

**Issue by HectorAlcoceba** [upm-space/geo-video-projection#1]
En las líneas 25 - 38 del código proyeccion.html se supone que debería cargar el objeto JSON del archivo AHR2.json, pero no lo hace.

**Comment by elgeografo** [comment]
Issue N1 corrected. I have incorporated the rest of the function inside the callback (this is wy it could not load the json). I have corrected also some mistakes  (se control version).
How the program fails in line 261 (Hector your turn) the mistake is easy to solve

**Comment by HectorAlcoceba** [comment]
Mistake in line 261 as well as some other minor mistakes solved and some unnecessary parts of the code removed.
